version: '3.7'

networks:
  logs:

services:

  grafana:
    image: grafana/grafana:8.1.3
    container_name: monitoring.grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - VIRTUAL_HOST=monitoring.grafana
      - NETWORK_ACCESS=internal
      - VIRTUAL_PORT=3000
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - logs

  loki:
    container_name: monitoring.loki
    image: grafana/loki:2.3.0
    expose:
      - 3100
    ports:
      - "3100:3100"
    volumes:
      - ${PWD}/loki:${PATH_TO_LOKI}
      - ${PWD}/loki/loki-data:/tmp/loki/
    command: -config.file=${PATH_TO_LOKI}/loki-config.yml
    restart: unless-stopped
    networks:
      - logs

  app:
    image: "mefaldemisov/devops_course:latest"
    container_name: devops_course
    ports:
      - "5000:5000"
    networks:
      - logs
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=python_app,environment=development
